<?xml version="1.0"?>
<html >
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="content-language" content="cs" />
    <meta name="robots" content="all,follow" />
 <title>LabourChauraha</title>
    <meta name="description" content="..." />
    <meta name="keywords" content="..." />
    
    <link rel="index" href="./" title="Home" />
    <link rel="stylesheet" media="screen,projection" type="text/css" href="./css/main.css" />
    <link rel="stylesheet" media="print" type="text/css" href="./css/print.css" />
    <link rel="stylesheet" media="aural" type="text/css" href="./css/aural.css" />
    <style type="text/css">

    </style>
</head>
<body>


<body >
<div style="background-image: url('design/blend.jpg'); background-repeat: no-repeat;
  background-position: top;
  margin-right: 0px;>"margine-up: 0px;>"<!-- Main -->
<div id="main" class="box">
<div class="login">
	    <form name="form1" method="post" action="otpcheck2.php">
        <table  border="0" style="margin-top:10px; margin-left:328px;">

					<tr>
                      <td><strong>Enter the OTP below</strong></td>
                    </tr>
                    <tr>
                     <td><span id="sprytextfield2">
                        <label>
                        <input type="varchar" name="REC" id="REC">
                        </label>
                      <span class="textfieldRequiredMsg">*</span></span></td>
                    </tr>
					
					<tr>
                      <td><label>
                        <div align="center">
                          <input type="submit" name="button" id="button" value="Validate">
                          </div>
                      </label></td>
                    </tr>
					
</table>
      </form>
              </div>
                <br/>
     
          </div> 
		  <tr>
					 
					  <br>
				
					  <br>
			
					 <br>
				
					 <br>
					 </br>
				
					 <br>
				
					  </br>
					
					  <br>
					  
					  </br>
				
					 <br>		  <br>
				
					  <br>
			
					 <br>
				
					 <br>
					 </br>
				
					 <br>
				
					  </br>
					
					  <br>
					  
					  </br>
				
					 <br>		  <br>
				
					  <br>
			
					 <br>
				
					 <br>
					 </br>
				
					 <br>
				
					  </br>
					
		
					  </br>
					
					  <br>
					  
					  </br>
				
					 <br>
					
					
</div>

</body>
		  
